### ISSUE TITLE
Documentation at https://matrixdepotjl.readthedocs.io/en/latest/interface.html is old

### ISSUE THREAD

**Issue by davidhrbac** [JuliaMatrices/MatrixDepot.jl#82] opened 2021-06-24 23:24 UTC
Site https://matrixdepotjl.readthedocs.io/en/latest/interface.html shows very old content not the latest one.

**Comment by willow-ahrens** [comment] 2022-07-25 15:35
@andreasnoack @KlausC How can I help fix this? It seems like there should be an easy fix by editing a CI script or something?

**Comment by KlausC** [comment] 2022-07-27 09:28
@willow-ahrens You are very welcome to dive into this. Currently I cannot see, if the issue is still valid.
If you find the generated docs are not in line with the doc sources, feel free to create a PR, which fixes the generation process.
I also except that in one of the CI scripts.

**Comment by willow-ahrens** [comment] 2022-07-27 14:03
Okay, here's what I know so far:

1. The documentation for the "adding custom generators" section is clearly out of date. The docs say they are from v0.5.6.

2. Documentation is hosted and build by readthedocs.io. Only people with accounts on readthedocs.io with the appropriate permissions can make changes to this setup. Who made the docs? Is the documentation not updating because the repository changed organization or something like that?

**Comment by willow-ahrens** [comment] 2022-07-27 14:22
The readthedocs page for MatrixDepot is https://readthedocs.org/projects/matrixdepotjl/, and it's pointing to the correct repo url. It looks like @weijianzhang is the owner of the account. It says the last build was 3 years ago. None of the releases listed on this github repo (v0.6ish and up) appear to have been built into docs. As far as I can tell, the last change that was built into documentation was bdec67eba6413d964582ee26c1cac2e72912b66b. Looking at the immediately following commits, I don't see anything that would cause the documentation to stop building.

**Comment by KlausC** [comment] 2022-07-27 16:57
In the meanwhile I found, that me (@KlausC) have a login to `readthedocs`, but I was not aware of the manual process of building the documentation. I fear @weijianzhang is no longer active in the project.
Would anybody mind, if I give access to you, @willow-ahrens?

**Comment by KlausC** [comment] 2022-07-27 21:31
The current doc is now https://matrix-depot.readthedocs.io/en/master .
That was obviously generated by my readthedocs-account. The builds with `stable` and `latest` seem to re-generate obsolete versions all the time, automatically.

**Comment by willow-ahrens** [comment] 2022-07-28 02:02
Feel free to give me access if you like. I'm not sure whether there's any other way to trigger a rebuild automatically, but just running builds manually seems like a good enough solution for now.

**Comment by willow-ahrens** [comment] 2022-07-28 02:02
Thanks for running the scripts! It does look like the docs are up to date now!

**Comment by KlausC** [comment] 2022-07-29 14:55
The link for the latest docu is now https://matrix-depot.readthedocs.io/en/latest/
It will be shown on README as soon as #97 is merged.

@willow-ahrens: I must have misunderstood my options. I have not the power to "give access". But you can register for "readthedocs.org" yourself.

**Closed** 2022-07-29 14:56 UTC
